### PR TITLE
fix: support vX.Y.Z semantic version

### PR DESCRIPTION
**Pull request by zoumo**
**What this PR does / why we need it**:

1. `blang/semver` doesn't support vX.Y.Z format version, use `Masterminds/semver` instead. `dep` uses `Masterminds/semver` too.
2. fix some typo error

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/cc @ddysher 

**Release note**:

```release-note
fix: support vX.Y.Z semantic version
```

### CODE REVIEW

**Comment by zoumo** [comment]
ping @ddysher

**Comment by deyuanix** [comment]
what's not supported? the prefix `v`?

**Comment by zoumo** [comment]
@ddysher 
1. `blang/semver` only support `X.Y.Z`, does not support the prefix `v`.
2.  `dep` uses `Masterminds/semver`. It comes from `glide`, I think it is the better choice.

**Pull request merged**
